metadata.format.version = "1.1"

[versions]

minestom = "f5f323fef9"

# Gradle plugins
blossom = "1.3.0"
shadowJar = "7.0.0"

[libraries]

minestom = { group = "com.github.Minestom", name = "Minestom", version.ref = "minestom" }

[bundles]

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadowJar = { id = "com.github.johnrengelman.shadow", version.ref = "shadowJar" }
